'use strict';const express=require('express');const pool=require('../db');const auth=require('../middleware/auth');const {hasConflict,enrollmentDecision,prorateCents,assertEnrollmentTransition}=require('../domain/studioPolicy');const router=express.Router();router.use(auth);
async function membership(client,tenantId,userId){const found=await client.query('SELECT role FROM dance_tenant_memberships WHERE tenant_id=$1 AND user_id=$2 AND active=true',[tenantId,userId]);if(!found.rows[0]){const error=new Error('studio membership required');error.status=403;throw error;}return found.rows[0].role;}
async function verifyTransitionEvidence(client,tenantId,enrollmentId,to,context){
  if(to==='dropped'){
    const ledgerId=Number(context.ledgerAdjustmentId);
    if(!Number.isSafeInteger(ledgerId)||ledgerId<=0)throw new Error('drop requires a persisted ledger adjustment id');
    const entry=(await client.query(`SELECT id,entry_type,policy_version FROM dance_ledger_entries WHERE id=$1 AND tenant_id=$2 AND entry_type IN ('refund','credit','proration') AND (enrollment_id=$3 OR enrollment_id IS NULL)`,[ledgerId,tenantId,enrollmentId])).rows[0];
    if(!entry)throw new Error('ledger adjustment not found for this tenant/enrollment');
    if(String(context.refundPolicyVersion)!==String(entry.policy_version))throw new Error('refundPolicyVersion does not match the stored ledger adjustment');
  }
  if(to==='completed'){
    const attendance=(await client.query('SELECT COUNT(*)::int AS n FROM dance_attendance_events WHERE enrollment_id=$1 AND tenant_id=$2',[enrollmentId,tenantId])).rows[0];
    if(!attendance||attendance.n<1)throw new Error('completion requires recorded attendance events for this enrollment');
  }
}
async function compactWaitlistPositions(client,sectionId){
  await client.query(`UPDATE dance_enrollments SET waitlist_position=waitlist_position+1000000 WHERE section_id=$1 AND status='waitlisted'`,[sectionId]);
  await client.query(`UPDATE dance_enrollments e SET waitlist_position=sub.rn FROM (SELECT id,ROW_NUMBER() OVER (ORDER BY waitlist_position,id) AS rn FROM dance_enrollments WHERE section_id=$1 AND status='waitlisted') sub WHERE e.id=sub.id AND e.waitlist_position IS DISTINCT FROM sub.rn`,[sectionId]);
}
router.post('/enrollments',async(req,res)=>{let client;try{client=await pool.connect();await client.query('BEGIN');const tenantId=String(req.body.tenantId||'');const key=String(req.get('Idempotency-Key')||'');if(!tenantId||!key)throw new Error('tenantId and Idempotency-Key are required');await membership(client,tenantId,req.user.id);const section=(await client.query('SELECT * FROM dance_sections WHERE id=$1 AND tenant_id=$2 FOR UPDATE',[req.body.sectionId,tenantId])).rows[0];if(!section)throw new Error('section not found');const student=(await client.query('SELECT * FROM dance_students WHERE id=$1 AND tenant_id=$2',[req.body.studentId,tenantId])).rows[0];if(!student)throw new Error('student not found');const slots=(await client.query(`SELECT s.starts_at AS "startsAt",s.ends_at AS "endsAt" FROM dance_enrollments e JOIN dance_sections s ON s.id=e.section_id WHERE e.student_id=$1 AND e.status='active'`,[student.id])).rows;const conflict=hasConflict(slots,{startsAt:section.starts_at,endsAt:section.ends_at});const consent=student.is_minor?(await client.query(`SELECT 1 FROM dance_consents WHERE student_id=$1 AND guardian_id=$2 AND purpose='program_participation' AND status='granted' AND granted_at<=NOW() AND expires_at>NOW()`,[student.id,req.body.guardianId])).rows[0]:true;const counts=await client.query(`SELECT COUNT(*)FILTER(WHERE status='active')::int AS enrolled,COUNT(*)FILTER(WHERE status='waitlisted')::int AS waitlisted FROM dance_enrollments WHERE section_id=$1`,[section.id]);const decision=enrollmentDecision({studentId:student.id,sectionId:section.id,studentAge:student.is_minor?17:18,guardianId:req.body.guardianId,guardianConsentActive:!!consent,scheduleConflict:conflict,enrolled:counts.rows[0].enrolled,capacity:section.capacity,waitlistCount:counts.rows[0].waitlisted});
const waitlistPosition=decision.status==='waitlisted'?Number((await client.query(`SELECT COALESCE(MAX(waitlist_position),0)+1 AS pos FROM dance_enrollments WHERE section_id=$1 AND status='waitlisted'`,[section.id])).rows[0].pos):null;
const tuition=prorateCents(section.term_amount_cents,new Date(section.term_starts_at),new Date(section.term_ends_at),new Date(req.body.enrollmentDate));const created=await client.query(`INSERT INTO dance_enrollments(tenant_id,student_id,section_id,status,status_reason,waitlist_position,tuition_cents,idempotency_key,created_by)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)ON CONFLICT(tenant_id,idempotency_key)DO UPDATE SET idempotency_key=EXCLUDED.idempotency_key RETURNING *`,[tenantId,student.id,section.id,decision.status,decision.reason,waitlistPosition,tuition,key,req.user.id]);await client.query(`INSERT INTO dance_audit_events(tenant_id,aggregate_type,aggregate_id,actor_id,action,payload)VALUES($1,'enrollment',$2,$3,'enrollment.requested',$4)`,[tenantId,created.rows[0].id,req.user.id,{decision,waitlistPosition,tuitionCents:tuition}]);await client.query('COMMIT');res.status(201).json(created.rows[0]);}catch(error){if(client)await client.query('ROLLBACK');res.status(error.status||422).json({error:error.message});}finally{client?.release();}});
router.post('/enrollments/:id/transition',async(req,res)=>{let client;try{client=await pool.connect();await client.query('BEGIN');const found=await client.query('SELECT * FROM dance_enrollments WHERE id=$1 FOR UPDATE',[req.params.id]);if(!found.rows[0]){const error=new Error('enrollment not found');error.status=404;throw error;}const record=found.rows[0];const role=await membership(client,record.tenant_id,req.user.id);const context=req.body.context||{};assertEnrollmentTransition(record.status,req.body.to,role,context);await verifyTransitionEvidence(client,record.tenant_id,record.id,req.body.to,context);const updated=await client.query('UPDATE dance_enrollments SET status=$1,version=version+1,updated_at=NOW()WHERE id=$2 AND version=$3 RETURNING *',[req.body.to,record.id,req.body.expectedVersion]);if(!updated.rows[0]){const error=new Error('version conflict');error.status=409;throw error;}if(record.status==='waitlisted'&&req.body.to!=='waitlisted'){await compactWaitlistPositions(client,record.section_id);}await client.query(`INSERT INTO dance_audit_events(tenant_id,aggregate_type,aggregate_id,actor_id,action,payload)VALUES($1,'enrollment',$2,$3,$4,$5)`,[record.tenant_id,record.id,req.user.id,`enrollment.${req.body.to}`,context]);await client.query('COMMIT');res.json(updated.rows[0]);}catch(error){if(client)await client.query('ROLLBACK');res.status(error.status||422).json({error:error.message});}finally{client?.release();}});
module.exports=router;
