'use strict';
function parseTime(value){const time=new Date(value);if(Number.isNaN(time.getTime()))throw new Error('invalid timestamp');return time;}
function hasConflict(existing,candidate){const start=parseTime(candidate.startsAt);const end=parseTime(candidate.endsAt);if(end<=start)throw new Error('class must end after it starts');return existing.some((slot)=>parseTime(slot.startsAt)<end&&parseTime(slot.endsAt)>start);}
function enrollmentDecision(input){if(!input||!input.studentId||!input.sectionId)throw new Error('studentId and sectionId are required');if(Number(input.studentAge)<18&&(!input.guardianId||input.guardianConsentActive!==true))throw new Error('active guardian consent is required for a minor');if(input.scheduleConflict===true)return{status:'blocked',reason:'schedule_conflict'};if(Number(input.enrolled)>=Number(input.capacity))return{status:'waitlisted',reason:'capacity',waitlistPosition:Number(input.waitlistCount||0)+1};return{status:'active',reason:null};}
function prorateCents(fullAmountCents,termStart,termEnd,enrollmentDate){if(!Number.isInteger(fullAmountCents)||fullAmountCents<0)throw new Error('amount must be non-negative integer cents');const start=parseTime(termStart),end=parseTime(termEnd),joined=parseTime(enrollmentDate);if(end<=start||joined<start||joined>end)throw new Error('invalid proration dates');const totalDays=Math.max(1,Math.ceil((end-start)/86400000));const activeDays=Math.max(0,Math.ceil((end-joined)/86400000));return Math.round(fullAmountCents*activeDays/totalDays);}
function refundCents(paidCents,attendedSessions,totalSessions,nonRefundableCents=0){if(![paidCents,attendedSessions,totalSessions,nonRefundableCents].every(Number.isInteger)||paidCents<0||attendedSessions<0||totalSessions<=0||attendedSessions>totalSessions||nonRefundableCents<0)throw new Error('invalid refund inputs');const earned=Math.round((paidCents-nonRefundableCents)*attendedSessions/totalSessions)+nonRefundableCents;return Math.max(0,paidCents-earned);}
function assertConsent(consent,purpose,at=new Date()){if(!consent||consent.status!=='granted'||consent.purpose!==purpose)throw new Error(`active ${purpose} consent required`);if(new Date(consent.expiresAt)<=at||new Date(consent.grantedAt)>at)throw new Error('consent is outside its validity window');return true;}
const TRANSITIONS={requested:['active','waitlisted','blocked'],waitlisted:['active','cancelled'],active:['completed','dropped','cancelled'],blocked:['requested'],dropped:[],cancelled:[],completed:[]};
function assertEnrollmentTransition(from,to,role,context={}){if(!(TRANSITIONS[from]||[]).includes(to))throw new Error(`invalid transition: ${from} -> ${to}`);if(!['registrar','manager','admin'].includes(role))throw new Error('registrar role required');if(to==='active'&&(!context.capacityReserved||context.scheduleConflict))throw new Error('activation requires reserved capacity and no conflict');if(to==='dropped'&&(!context.ledgerAdjustmentId||!context.refundPolicyVersion))throw new Error('drop requires a versioned ledger adjustment');if(to==='completed'&&!context.attendanceReconciled)throw new Error('completion requires reconciled attendance');return true;}
module.exports={hasConflict,enrollmentDecision,prorateCents,refundCents,assertConsent,assertEnrollmentTransition};
